version: '3.8'

services:
  conciliacion-app:
    # Construye la imagen usando el Dockerfile de esta carpeta actual
    build: . 
    container_name: app_conciliacion_bancaria
    restart: always
    ports:
      # Mapea el puerto externo 8502 al interno 8501
      - "8502:8501"
    volumes:
      # Conecta la carpeta actual (.) con la del contenedor (/app)
      - ./:/app
    # IMPORTANTE: Le dice que ejecute tu archivo espec√≠fico, no el default
    command: streamlit run conciliacion_bancaria.py