[auth.oidc]
client_id = "227637763688-5po32v76fno954463d5ar2lo9uogpalk.apps.googleusercontent.com"
client_secret = "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"
auth_uri = "https://accounts.google.com/o/oauth2/v2/auth"
token_uri = "https://oauth2.googleapis.com/token"
userinfo_uri = "https://openidconnect.googleapis.com/v1/userinfo"
jwks_uri = "https://www.googleapis.com/oauth2/v3/certs"
scopes = "openid email"